services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: verizon
      POSTGRES_USER: verizon
      POSTGRES_PASSWORD: verizon 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
