interpret_sql_results_task:
  description: >
    <Task>
      Interpret raw SQL query outputs and transform them into meaningful business insights.
    </Task>

    <Inputs>
      You are given:
      - The original user request: {user_prompt}
      - The SQL query that was executed: {sql_query}
      - The raw SQL output: {sql_results}
      - Today's date: {date}
    </Inputs>

    <Database Context>
      The underlying schema includes:
        1. Projects — project_id, market, site_type, start/end dates.
        2. Agents — agent_id, agent_name, description.
        3. Milestones — milestone_id, project_id, agent_id, milestone_name, planned/actual dates, status, anomaly_flag.
        4. Dependencies — milestone dependencies (prerequisite, successor).
        5. Vendors — vendor_id, vendor_name, role.
        6. Milestone_Vendors — join table milestone_id ↔ vendor_id.
        7. Anomalies — anomaly_id, milestone_id, type, severity, description, detected_on.
        8. Cycle_Times — cycle_id, project_id, agent_start_id, agent_end_id, planned vs. actual duration, variance.
    </Database Context>

    <Audience>
      Business leaders, program managers, and engineers who need actionable insights
      rather than raw numbers.
    </Audience>

    <Instructions>
      1. Summarize the main findings in plain language (e.g., "Market A projects
         are delayed by an average of 14 days compared to plan").
      2. Highlight anomalies, outliers, or unexpected results.
      3. Explain *why* results might look this way using schema context (e.g.,
         "delays tied to vendor X", "agent Y has most anomalies").
      4. Suggest next steps or follow-up questions for the business.
      5. Be concise but detailed: avoid just restating the raw numbers.
    </Instructions>

    <Examples>
      **Example 1 (Milestone delays by vendor):**
        "Vendor A shows the highest average milestone delay at 12.5 days,
        mostly tied to Construction-related milestones in Market B.
        Vendor B performed consistently with minimal delays.
        This suggests Vendor A’s resource allocation is a risk point."

      **Example 2 (Cycle efficiency):**
        "Across 80 cycles, average variance between planned and actual duration
        was +6 days. RF → Construction transitions contributed 70% of delays,
        highlighting a bottleneck between engineering and build-out phases."
    </Examples>
  expected_output: >
    <Output Format>
    {{
        "summary": "Plain-language interpretation of the results",
        "patterns": ["List of notable trends"],
        "anomalies": ["Outliers, risks, issues"],
        "recommendations": ["Concrete actions or next steps"]
    }}
    </Output Format>
  agent: result_analysis_agent
